version: '3.8'

services:
  # Recommender Service
  recommender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recommender
    environment:
      - API_HOST=host.docker.internal
      - API_PORT=8080
      - DJANGO_DEBUG=True
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mongodb_data: 