services:
  # Recommender Service
  recommender:
    build: .
    container_name: eduforge-recommender
    environment:
      - EXTERNAL_API_URL=http://eduforge-post-app:8080
    ports:
      - "8090:8000"
    volumes:
      - recommender_data:/app/data
    networks:
      - eduforge-network
    restart: always

networks:
  eduforge-network:
    external: true
    name: eduforge-network

volumes:
  mongodb_data:
  recommender_data: 