services:
  # Recommender Service
  recommender:
    build: .
    container_name: eduforge-recommender
    ports:
      - "8090:8090"
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    networks:
      - eduforge-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/v1/interactions/train_and_recommend/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
networks:
  eduforge-network:
    external: true
    name: eduforge-network