services:
  # Recommender Service
  recommender:
    build: .
    container_name: eduforge-recommender
    ports:
      - "8090:8000"
    environment:
      - EXTERNAL_API_URL=http://eduforge-post-app:8080
      - PYTHONUNBUFFERED=1
    networks:
      - eduforge-network
    restart: always

networks:
  eduforge-network:
    external: true
    name: eduforge-network

volumes:
  recommender_data: 